//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace WinForms.Ribbon
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint ApplicationMenu = 3;
            public const uint RecentItemsCaption = 4;
            public const uint btnNewWindow = 2;
            public const uint sbgCliHere = 14;
            public const uint btnSettings = 8;
            public const uint sbAbout = 12;
            public const uint btnAbout = 9;
            public const uint mngAbout = 10;
            public const uint btnAboutWin = 11;
            public const uint btnExit = 13;
            public const uint HelpButton = 5;
            public const uint QAT = 6;
            public const uint btnRename = 53;
            public const uint btnDelete = 54;
            public const uint btnProperties = 90;
            public const uint btnOpen = 86;
            public const uint ctabPicTools = 25;
            public const uint tabPicture = 26;
            public const uint ctabImgTools = 27;
            public const uint tabDskImg = 28;
            public const uint ctabArchiveTools = 29;
            public const uint tabArchive = 30;
            public const uint ctabExeTools = 31;
            public const uint tabExe = 33;
            public const uint ctabScriptTools = 34;
            public const uint tabScript = 35;
            public const uint ctabDriveTools = 36;
            public const uint tabDrive = 37;
            public const uint ctabComputer = 38;
            public const uint tabThisPC = 39;
            public const uint tabHome = 20;
            public const uint grpClipboard = 40;
            public const uint sbCopy = 42;
            public const uint btnCopy = 41;
            public const uint btnCopyPath = 43;
            public const uint sbPaste = 47;
            public const uint btnPaste = 46;
            public const uint btnPasteLink = 48;
            public const uint btnCut = 49;
            public const uint sbgCopyTo = 44;
            public const uint btnBrowseCopyTo = 45;
            public const uint sbgMoveTo = 50;
            public const uint btnBrowseMoveTo = 51;
            public const uint grpOperations = 52;
            public const uint btnPermDelete = 55;
            public const uint chbConfirmDelete = 57;
            public const uint btnRecycleBin = 56;
            public const uint btnRunAs = 87;
            public const uint ddgRunOptions = 88;
            public const uint btnOpenWith = 89;
            public const uint grpNew = 58;
            public const uint btnNewDir = 59;
            public const uint btnNewText = 60;
            public const uint btnNewShortcut = 61;
            public const uint ddbNewOptions = 62;
            public const uint mngTextFiles = 63;
            public const uint btnMkFTxt = 64;
            public const uint btnMkFMd = 65;
            public const uint btnMkFRtf = 66;
            public const uint mngConfFiles = 67;
            public const uint btnMkFXml = 68;
            public const uint btnMkFJson = 69;
            public const uint btnMkFIni = 70;
            public const uint mngLinkFiles = 71;
            public const uint btnMkFLnk = 72;
            public const uint btnMkFUrl = 74;
            public const uint btnMkFSl = 73;
            public const uint mngScriptFiles = 75;
            public const uint btnMkFBat = 76;
            public const uint btnMkFCmd = 77;
            public const uint btnMkFPs1 = 78;
            public const uint btnMkFSh = 79;
            public const uint btnMkFFCmd = 80;
            public const uint mngCodeFiles = 81;
            public const uint btnMkFCs = 82;
            public const uint btnMkFCpp = 83;
            public const uint btnMkFC = 84;
            public const uint btnMkFPy = 85;
            public const uint tabBrowse = 21;
            public const uint grpNavigation = 91;
            public const uint btnBack = 92;
            public const uint btnFwd = 93;
            public const uint btnUp = 94;
            public const uint btnThisPC = 95;
            public const uint grpPath = 96;
            public const uint btnGoToPath = 97;
            public const uint btnFind = 98;
            public const uint tabSecurity = 22;
            public const uint grpPerms = 99;
            public const uint btnViewAcl = 100;
            public const uint btnEditAcl = 101;
            public const uint grpOwnership = 102;
            public const uint tabView = 23;
            public const uint tabTools = 24;
            public const uint btnCustomizeQat = 7;
        }

        // ContextPopup CommandName

        public RibbonStrip Ribbon { get; private set; }
        public RibbonApplicationMenu ApplicationMenu { get; private set; }
        public RibbonRecentItems RecentItemsCaption { get; private set; }
        public RibbonButton btnNewWindow { get; private set; }
        public RibbonSplitButtonGallery sbgCliHere { get; private set; }
        public RibbonButton btnSettings { get; private set; }
        public RibbonSplitButton sbAbout { get; private set; }
        public RibbonButton btnAbout { get; private set; }
        public RibbonMenuGroup mngAbout { get; private set; }
        public RibbonButton btnAboutWin { get; private set; }
        public RibbonButton btnExit { get; private set; }
        public RibbonHelpButton HelpButton { get; private set; }
        public RibbonQuickAccessToolbar QAT { get; private set; }
        public RibbonButton btnRename { get; private set; }
        public RibbonButton btnDelete { get; private set; }
        public RibbonButton btnProperties { get; private set; }
        public RibbonButton btnOpen { get; private set; }
        public RibbonTabGroup ctabPicTools { get; private set; }
        public RibbonTab tabPicture { get; private set; }
        public RibbonTabGroup ctabImgTools { get; private set; }
        public RibbonTab tabDskImg { get; private set; }
        public RibbonTabGroup ctabArchiveTools { get; private set; }
        public RibbonTab tabArchive { get; private set; }
        public RibbonTabGroup ctabExeTools { get; private set; }
        public RibbonTab tabExe { get; private set; }
        public RibbonTabGroup ctabScriptTools { get; private set; }
        public RibbonTab tabScript { get; private set; }
        public RibbonTabGroup ctabDriveTools { get; private set; }
        public RibbonTab tabDrive { get; private set; }
        public RibbonTabGroup ctabComputer { get; private set; }
        public RibbonTab tabThisPC { get; private set; }
        public RibbonTab tabHome { get; private set; }
        public RibbonGroup grpClipboard { get; private set; }
        public RibbonSplitButton sbCopy { get; private set; }
        public RibbonButton btnCopy { get; private set; }
        public RibbonButton btnCopyPath { get; private set; }
        public RibbonSplitButton sbPaste { get; private set; }
        public RibbonButton btnPaste { get; private set; }
        public RibbonButton btnPasteLink { get; private set; }
        public RibbonButton btnCut { get; private set; }
        public RibbonSplitButtonGallery sbgCopyTo { get; private set; }
        public RibbonButton btnBrowseCopyTo { get; private set; }
        public RibbonSplitButtonGallery sbgMoveTo { get; private set; }
        public RibbonButton btnBrowseMoveTo { get; private set; }
        public RibbonGroup grpOperations { get; private set; }
        public RibbonButton btnPermDelete { get; private set; }
        public RibbonCheckBox chbConfirmDelete { get; private set; }
        public RibbonButton btnRecycleBin { get; private set; }
        public RibbonButton btnRunAs { get; private set; }
        public RibbonDropDownGallery ddgRunOptions { get; private set; }
        public RibbonButton btnOpenWith { get; private set; }
        public RibbonGroup grpNew { get; private set; }
        public RibbonButton btnNewDir { get; private set; }
        public RibbonButton btnNewText { get; private set; }
        public RibbonButton btnNewShortcut { get; private set; }
        public RibbonDropDownButton ddbNewOptions { get; private set; }
        public RibbonMenuGroup mngTextFiles { get; private set; }
        public RibbonButton btnMkFTxt { get; private set; }
        public RibbonButton btnMkFMd { get; private set; }
        public RibbonButton btnMkFRtf { get; private set; }
        public RibbonMenuGroup mngConfFiles { get; private set; }
        public RibbonButton btnMkFXml { get; private set; }
        public RibbonButton btnMkFJson { get; private set; }
        public RibbonButton btnMkFIni { get; private set; }
        public RibbonMenuGroup mngLinkFiles { get; private set; }
        public RibbonButton btnMkFLnk { get; private set; }
        public RibbonButton btnMkFUrl { get; private set; }
        public RibbonButton btnMkFSl { get; private set; }
        public RibbonMenuGroup mngScriptFiles { get; private set; }
        public RibbonButton btnMkFBat { get; private set; }
        /// <summary>
        /// technically the same as BAT
        /// </summary>
        public RibbonButton btnMkFCmd { get; private set; }
        public RibbonButton btnMkFPs1 { get; private set; }
        public RibbonButton btnMkFSh { get; private set; }
        public RibbonButton btnMkFFCmd { get; private set; }
        public RibbonMenuGroup mngCodeFiles { get; private set; }
        public RibbonButton btnMkFCs { get; private set; }
        public RibbonButton btnMkFCpp { get; private set; }
        public RibbonButton btnMkFC { get; private set; }
        public RibbonButton btnMkFPy { get; private set; }
        public RibbonTab tabBrowse { get; private set; }
        public RibbonGroup grpNavigation { get; private set; }
        public RibbonButton btnBack { get; private set; }
        public RibbonButton btnFwd { get; private set; }
        public RibbonButton btnUp { get; private set; }
        public RibbonButton btnThisPC { get; private set; }
        public RibbonGroup grpPath { get; private set; }
        public RibbonButton btnGoToPath { get; private set; }
        public RibbonButton btnFind { get; private set; }
        public RibbonTab tabSecurity { get; private set; }
        public RibbonGroup grpPerms { get; private set; }
        public RibbonButton btnViewAcl { get; private set; }
        public RibbonButton btnEditAcl { get; private set; }
        public RibbonGroup grpOwnership { get; private set; }
        public RibbonTab tabView { get; private set; }
        public RibbonTab tabTools { get; private set; }

        public RibbonItems(RibbonStrip ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ApplicationMenu = new RibbonApplicationMenu(ribbon, Cmd.ApplicationMenu);
            RecentItemsCaption = new RibbonRecentItems(ribbon, Cmd.RecentItemsCaption);
            btnNewWindow = new RibbonButton(ribbon, Cmd.btnNewWindow);
            sbgCliHere = new RibbonSplitButtonGallery(ribbon, Cmd.sbgCliHere);
            btnSettings = new RibbonButton(ribbon, Cmd.btnSettings);
            sbAbout = new RibbonSplitButton(ribbon, Cmd.sbAbout);
            btnAbout = new RibbonButton(ribbon, Cmd.btnAbout);
            mngAbout = new RibbonMenuGroup(ribbon, Cmd.mngAbout);
            btnAboutWin = new RibbonButton(ribbon, Cmd.btnAboutWin);
            btnExit = new RibbonButton(ribbon, Cmd.btnExit);
            HelpButton = new RibbonHelpButton(ribbon, Cmd.HelpButton);
            QAT = new RibbonQuickAccessToolbar(ribbon, Cmd.QAT, Cmd.btnCustomizeQat);
            btnRename = new RibbonButton(ribbon, Cmd.btnRename);
            btnDelete = new RibbonButton(ribbon, Cmd.btnDelete);
            btnProperties = new RibbonButton(ribbon, Cmd.btnProperties);
            btnOpen = new RibbonButton(ribbon, Cmd.btnOpen);
            ctabPicTools = new RibbonTabGroup(ribbon, Cmd.ctabPicTools);
            tabPicture = new RibbonTab(ribbon, Cmd.tabPicture);
            ctabImgTools = new RibbonTabGroup(ribbon, Cmd.ctabImgTools);
            tabDskImg = new RibbonTab(ribbon, Cmd.tabDskImg);
            ctabArchiveTools = new RibbonTabGroup(ribbon, Cmd.ctabArchiveTools);
            tabArchive = new RibbonTab(ribbon, Cmd.tabArchive);
            ctabExeTools = new RibbonTabGroup(ribbon, Cmd.ctabExeTools);
            tabExe = new RibbonTab(ribbon, Cmd.tabExe);
            ctabScriptTools = new RibbonTabGroup(ribbon, Cmd.ctabScriptTools);
            tabScript = new RibbonTab(ribbon, Cmd.tabScript);
            ctabDriveTools = new RibbonTabGroup(ribbon, Cmd.ctabDriveTools);
            tabDrive = new RibbonTab(ribbon, Cmd.tabDrive);
            ctabComputer = new RibbonTabGroup(ribbon, Cmd.ctabComputer);
            tabThisPC = new RibbonTab(ribbon, Cmd.tabThisPC);
            tabHome = new RibbonTab(ribbon, Cmd.tabHome);
            grpClipboard = new RibbonGroup(ribbon, Cmd.grpClipboard);
            sbCopy = new RibbonSplitButton(ribbon, Cmd.sbCopy);
            btnCopy = new RibbonButton(ribbon, Cmd.btnCopy);
            btnCopyPath = new RibbonButton(ribbon, Cmd.btnCopyPath);
            sbPaste = new RibbonSplitButton(ribbon, Cmd.sbPaste);
            btnPaste = new RibbonButton(ribbon, Cmd.btnPaste);
            btnPasteLink = new RibbonButton(ribbon, Cmd.btnPasteLink);
            btnCut = new RibbonButton(ribbon, Cmd.btnCut);
            sbgCopyTo = new RibbonSplitButtonGallery(ribbon, Cmd.sbgCopyTo);
            btnBrowseCopyTo = new RibbonButton(ribbon, Cmd.btnBrowseCopyTo);
            sbgMoveTo = new RibbonSplitButtonGallery(ribbon, Cmd.sbgMoveTo);
            btnBrowseMoveTo = new RibbonButton(ribbon, Cmd.btnBrowseMoveTo);
            grpOperations = new RibbonGroup(ribbon, Cmd.grpOperations);
            btnPermDelete = new RibbonButton(ribbon, Cmd.btnPermDelete);
            chbConfirmDelete = new RibbonCheckBox(ribbon, Cmd.chbConfirmDelete);
            btnRecycleBin = new RibbonButton(ribbon, Cmd.btnRecycleBin);
            btnRunAs = new RibbonButton(ribbon, Cmd.btnRunAs);
            ddgRunOptions = new RibbonDropDownGallery(ribbon, Cmd.ddgRunOptions);
            btnOpenWith = new RibbonButton(ribbon, Cmd.btnOpenWith);
            grpNew = new RibbonGroup(ribbon, Cmd.grpNew);
            btnNewDir = new RibbonButton(ribbon, Cmd.btnNewDir);
            btnNewText = new RibbonButton(ribbon, Cmd.btnNewText);
            btnNewShortcut = new RibbonButton(ribbon, Cmd.btnNewShortcut);
            ddbNewOptions = new RibbonDropDownButton(ribbon, Cmd.ddbNewOptions);
            mngTextFiles = new RibbonMenuGroup(ribbon, Cmd.mngTextFiles);
            btnMkFTxt = new RibbonButton(ribbon, Cmd.btnMkFTxt);
            btnMkFMd = new RibbonButton(ribbon, Cmd.btnMkFMd);
            btnMkFRtf = new RibbonButton(ribbon, Cmd.btnMkFRtf);
            mngConfFiles = new RibbonMenuGroup(ribbon, Cmd.mngConfFiles);
            btnMkFXml = new RibbonButton(ribbon, Cmd.btnMkFXml);
            btnMkFJson = new RibbonButton(ribbon, Cmd.btnMkFJson);
            btnMkFIni = new RibbonButton(ribbon, Cmd.btnMkFIni);
            mngLinkFiles = new RibbonMenuGroup(ribbon, Cmd.mngLinkFiles);
            btnMkFLnk = new RibbonButton(ribbon, Cmd.btnMkFLnk);
            btnMkFUrl = new RibbonButton(ribbon, Cmd.btnMkFUrl);
            btnMkFSl = new RibbonButton(ribbon, Cmd.btnMkFSl);
            mngScriptFiles = new RibbonMenuGroup(ribbon, Cmd.mngScriptFiles);
            btnMkFBat = new RibbonButton(ribbon, Cmd.btnMkFBat);
            btnMkFCmd = new RibbonButton(ribbon, Cmd.btnMkFCmd);
            btnMkFPs1 = new RibbonButton(ribbon, Cmd.btnMkFPs1);
            btnMkFSh = new RibbonButton(ribbon, Cmd.btnMkFSh);
            btnMkFFCmd = new RibbonButton(ribbon, Cmd.btnMkFFCmd);
            mngCodeFiles = new RibbonMenuGroup(ribbon, Cmd.mngCodeFiles);
            btnMkFCs = new RibbonButton(ribbon, Cmd.btnMkFCs);
            btnMkFCpp = new RibbonButton(ribbon, Cmd.btnMkFCpp);
            btnMkFC = new RibbonButton(ribbon, Cmd.btnMkFC);
            btnMkFPy = new RibbonButton(ribbon, Cmd.btnMkFPy);
            tabBrowse = new RibbonTab(ribbon, Cmd.tabBrowse);
            grpNavigation = new RibbonGroup(ribbon, Cmd.grpNavigation);
            btnBack = new RibbonButton(ribbon, Cmd.btnBack);
            btnFwd = new RibbonButton(ribbon, Cmd.btnFwd);
            btnUp = new RibbonButton(ribbon, Cmd.btnUp);
            btnThisPC = new RibbonButton(ribbon, Cmd.btnThisPC);
            grpPath = new RibbonGroup(ribbon, Cmd.grpPath);
            btnGoToPath = new RibbonButton(ribbon, Cmd.btnGoToPath);
            btnFind = new RibbonButton(ribbon, Cmd.btnFind);
            tabSecurity = new RibbonTab(ribbon, Cmd.tabSecurity);
            grpPerms = new RibbonGroup(ribbon, Cmd.grpPerms);
            btnViewAcl = new RibbonButton(ribbon, Cmd.btnViewAcl);
            btnEditAcl = new RibbonButton(ribbon, Cmd.btnEditAcl);
            grpOwnership = new RibbonGroup(ribbon, Cmd.grpOwnership);
            tabView = new RibbonTab(ribbon, Cmd.tabView);
            tabTools = new RibbonTab(ribbon, Cmd.tabTools);
        }

    }
}
